version: '3.7'
services:
  api:
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    networks:
      - vlab_network
    volumes:
      - ./vlab_network:/shared
    deploy:
      resources:
        limits:
          memory: 512M
  app:
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - vlab_network
    volumes:
      - ./vlab_network:/shared
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  vlab_network:

volumes:
  vlab_volume: