version: '3.7'
services:
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    ports:
      - "5005:5005"
    networks:
      - vlab_network
    volumes:
      - shared_volume:/usr/src/app/shared
    deploy:
      resources:
        limits:
          memory: 512M
  app:
    build:
      context: ./ui/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - vlab_network
    volumes:
      - shared_volume:/usr/src/app/shared
    depends_on:
      - api
    deploy:
      resources:
        limits:
          memory: 512M

networks:
  vlab_network:

volumes:
    shared_volume: